spring:
  application:
    name: mobilelele
  thymeleaf:
    check-template: true
    cache: false
    prefix: file:./src/main/resources/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
#  properties:
#    hibernate:
#      jdbc:
#        url: jdbc:mysql://localhost:3306/mobilelele?useSSL=false&serverTimezone=UTC  # Set JDBC URL for Hibernate
#      dialect: org.hibernate.dialect.MySQLDialect  # Set the dialect
  sql:
    init:
      mode: never

  mvc:
    hiddenmethod:
      filter:
        enabled: true